<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;

echo "--- STARTING DATABASE REPAIR ---\n";

try {
    // 1. Drop if exists
    if (Schema::hasTable('virtual_classes')) {
        Schema::drop('virtual_classes');
        echo "Dropped existing 'virtual_classes' table.\n";
    }

    // 2. Create Table
    Schema::create('virtual_classes', function (Blueprint $table) {
        $table->id();
        // Making FKs nullable for safety in this emergency script
        $table->foreignId('course_id')->nullable(); 
        $table->foreignId('lecturer_id')->nullable();
        $table->string('title');
        $table->text('description')->nullable();
        $table->dateTime('scheduled_at')->nullable();
        $table->integer('duration')->default(60);
        $table->string('meeting_link')->nullable();
        $table->string('recording_url')->nullable();
        $table->boolean('is_recorded')->default(false);
        $table->enum('status', ['upcoming', 'active', 'ended'])->default('upcoming');
        $table->timestamps();
    });
    echo "Created 'virtual_classes' table successfully.\n";

    // 3. Seed One Row
    DB::table('virtual_classes')->insert([
        'title' => 'System Check Class',
        'description' => 'Auto-generated by repair script',
        'scheduled_at' => \Carbon\Carbon::now()->addDay(),
        'status' => 'upcoming',
        'created_at' => now(),
        'updated_at' => now()
    ]);
    echo "Seeded test data.\n";

} catch (\Exception $e) {
    echo "ERROR: " . $e->getMessage() . "\n";
    exit(1);
}

echo "--- REPAIR COMPLETE ---\n";
